### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [mvicera/jQuery_Style_Switcher#1]
Marc,

Nice job! Everything looks here minus the overlay feature. As discussed in class, this will be an empty div with a position fixed:

```css
.overlay {
  position:fixed;
  top:0;
  left:0;
  width:100%;
  height:100%;
  background-color:rgba(0,0,0,0.5);
}
```
